id: IFDC527DE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T08:16:18+00:00'
last_modified: '2022-06-08T05:12:29.483962+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2EE7
  title: ཐར་པ་ཆེན་པོའི་མདོ།（སོག་ཡིག）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FF72:
      image_group_id: I1KG16882
      title: Volume 1 of thar pa chen po'i mdo/（sog yig）
      total_pages: 242
      order: 1
      base_file: FF72.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
